let cmAltura = 179;
let mAltura = 1.79;
let pesoKg = 93.54;
let alturaRedondeadaArriba = Math.round(mAltura);
let alturaRedondeadaAbajo = Math.floor(mAltura);
let maxValor = Number.MAX_VALUE + 1;
let esMaxIgual = maxValor === Number.MAX_VALUE;
console.log(alturaRedondeadaArriba);
console.log(alturaRedondeadaAbajo);
console.log(maxValor);
console.log(esMaxIgual);